"""Redis 缓存管理"""

# TODO: 实现
# from redis.asyncio import Redis
#
# class CacheManager:
#     """Redis 缓存管理层"""
#
#     async def get_or_set(self, key: str, ttl: int, factory): ...
#     async def cache_poi_list(self, key: str, pois: list, ttl=600): ...
#     async def cache_llm_response(self, prompt_hash: str, response: str, ttl=3600): ...
#     async def get_cached_llm_response(self, prompt_hash: str) -> str | None: ...
raise NotImplementedError
